<?php
$header = array("Auditor Name", "Audit Date", "Fusion ID", "Agent Name", "L1 Supervisor", "Manager", "AHT RCA","Phone Number","Customer Name", "Call Date", "Call Duration", "Audit Type", "Auditor Type", "VOC","Possible Score", "Earned Score", "Overall Score",
		  "Identify himself/herself by first and last name at the beginning of the call? **SQ**",
		   "Provide the Quality Assurance Statement verbatim, before any specific account information was discussed?**SQ**",
		    "State My Quick Wallet with no deviation? **SQ**",
		  "Verify that he/she was speaking to a right party according to the client requirements (First and Last Name) and before providing the disclosures?",
		  "Verify two pieces of demographics information on an outbound call?
Any two of: (1) Full Name (2) Date of Birth (3) Last four digits of SSN (4)Email Address ",
		  "Provide the Mini Miranda disclosure verbatim before any specific account information was discussed? **SQ**",
		  "Did the rep ask for callback permission as per Reg F policy?",
		  "State/Ask for balance due? (If required also inform the breakdown of principal finance fees & NSF Fees.)",
		  "Ask for intention to resolve the account?",
		  "Ask for the payment to the account?",
		  "Followed the previous conversations on the account for the follow-up call",
		  "Able to take a promise to pay on the account?",
		  "Did the collector elaborate the consiquences of not clearing the bills and benefits of paying off? Eg.
a) Not paying off your debt will prevent your ability to get short term loans with our company and perhaps other companies
b) Paying off will allow you to apply for a new loan in the future
c) Finance fees may continue to be added to your balance if no payments are being made",
		  "Did the collector provide applicable settelment options? Eg.
a) We are willing to set up a payment plan on your paydays to pay this off in smaller payments over the next 1 -2 months.",
		  "Could the collector manage to create urgency for payment? Eg.
a) We may be required to reach out to your employer for verification of employment",
		  "Did Collector try to negotiate effectively to convince the customer for payment with all possible options?",
		  "Did not  Misrepresent their identity or authorization and status of the consumers account?",
		  "Did not Discuss or imply that any type of legal actions - will be taken or property repossessed also on time barred accounts amd Did not Threaten to take actions that the client cannot legally take?",
		  "Did not Make any false representations regarding the nature of the communication?",
		  "Did not Contact the consumer at any unusual times (sate regulations) or outside the hours of 8:00 am and 9:00 pm at the consumers location?",
		  "Did not Communicate with the consumer at work if it is known or there is reason to know that such calls are prohibited?",
		  "Did not Communicate with the consumer after learning the consumer is represented by an attorney filed for bankruptcy unless a permissible reason exists?",
		  "Adhere to the cell phone policy/TCPA regulations and policy regarding contacting consumers via cell phone email and fax?",
		  "Adhere to policy regarding third parties for the sole purpose of obtaining location information for the consumer?",
		  "Enter Status code/disposition codes correctly to ensure that inappropriate dialing does not take place?",
		  "Did not Make any statement that could constitute unfair deceptive or abusive acts or practices that may raise UDAAP concerns?",
		  "Did not Communicate or threaten to communicate false credit information or information which should be known to be false and utilized the proper CBR script whenever a consumer enquires about that?",
		  "Handle the consumers dispute correctly and take appropriate action including providing the consumer with the correct contact information to submit a written dispute or complaint or offer to escalate the call?",
		  "Did not Make the required statement on time barred accounts indicating that the consumer cannot be pursued with legal action?",
		  "Adhere to FDCPA  laws?",
		  "Did not Make any statement that could be considered discriminatory towards a consumer or a violation ECOA policy?",
		  "Did the collectors adhere to the State Restrictions?",
		  "Confirm with consumer if he/she is the authorized user of the debit or credit card / checking account?",
		  "Recap the call by verifying consumers Name Address CC/AP information?",
		  "Stated the proper payment script before processing payment?",
		  "Obtain permission from the consumer to initiate electronic credit /debit card transactions or through checking account and get supervisor verification if needed?**SQ**",
		  "Educate the consumer about correspondence being sent (Receipts PIF SIF Confirmations etc)?",
		  "In case of PDCs did the Collector asks for permission to call the Consumer back if it is declined or there is an issue with the payment? ",
		  "Demonstrate Active Listening?",
		  "Represent the company and the client in a positive manner?",
		  "Anticipate and overcome objections?",
		  "Transfer call to My Quick Wallets support appropriately (if applicable)?",
		  "Summarize the call?",
		  "Provided My Quick Wallet's support number incase its required (if applicable)?",
		  "Set appropriate timelines and expectations for follow up?",
		  "Close the call Professionally?",
		  "Use the proper action code?",
		  "Use the proper result code?",
		  "Document thoroughly the context of the conversation?",
		  "Did the rep document the callback permission on the account as per Reg F policy?",
		  "Remove any phone numbers known to be incorrect?**SQ**",
		  "Update address information if appropriate?**SQ**",
		  "Change the status of the account, if appropriate?**SQ**",
		  "Escalate the account to a supervisor for handling, if appropriate?",

		  "Identify himself/herself by first and last name at the beginning of the call? **SQ** - Remarks", 
		  "Provide the Quality Assurance Statement verbatim, before any specific account information was discussed?**SQ** -Remarks", 
		  "State My Quick Wallet with no deviation? **SQ**- Remarks",
		  "Verify that he/she was speaking to a right party according to the client requirements (First and Last Name) and before providing the disclosures? - Remarks",
		  "Verify two pieces of demographics information on an outbound call?
Any two of: (1) Full Name (2) Date of Birth (3) Last four digits of SSN (4)Email Address - Remarks",
		  "Provide the Mini Miranda disclosure verbatim before any specific account information was discussed? **SQ** - Remarks",
		  "Did the rep ask for callback permission as per Reg F policy? - Remarks",
		  "State/Ask for balance due? (If required also inform the breakdown of principal finance fees & NSF Fees.)- Remarks",
		  "Ask for intention to resolve the account? - Remarks",
		  "Ask for the payment to the account? - Remarks",
		  "Followed the previous conversations on the account for the follow-up call - Remarks",
		  "Able to take a promise to pay on the account? - Remarks",
		  "Did the collector elaborate the consiquences of not clearing the bills and benefits of paying off? Eg.
a) Not paying off your debt will prevent your ability to get short term loans with our company and perhaps other companies
b) Paying off will allow you to apply for a new loan in the future
c) Finance fees may continue to be added to your balance if no payments are being made - Remarks",
		  "Did the collector provide applicable settelment options? Eg.
a) We are willing to set up a payment plan on your paydays to pay this off in smaller payments over the next 1 -2 months. - Remarks",
		  "Could the collector manage to create urgency for payment? Eg.
a) We may be required to reach out to your employer for verification of employment - Remarks",
		  "Did Collector try to negotiate effectively to convince the customer for payment with all possible options? - Remarks",
		  "Did not  Misrepresent their identity or authorization and status of the consumers account? - Remarks",
		  "Did not Discuss or imply that any type of legal actions - will be taken or property repossessed also on time barred accounts amd Did not Threaten to take actions that the client cannot legally take? - Remarks",
		  "Did not Make any false representations regarding the nature of the communication? - Remarks",
		  "Did not Contact the consumer at any unusual times (sate regulations) or outside the hours of 8:00 am and 9:00 pm at the consumers location? - Remarks",
		  "Did not Communicate with the consumer at work if it is known or there is reason to know that such calls are prohibited? - Remarks",
		  "Did not Communicate with the consumer after learning the consumer is represented by an attorney filed for bankruptcy unless a permissible reason exists? - Remarks",
		  "Adhere to the cell phone policy/TCPA regulations and policy regarding contacting consumers via cell phone email and fax? - Remarks",
		  "Adhere to policy regarding third parties for the sole purpose of obtaining location information for the consumer? - Remarks",
		  "Enter Status code/disposition codes correctly to ensure that inappropriate dialing does not take place? - Remarks",
		  "Did not Make any statement that could constitute unfair deceptive or abusive acts or practices that may raise UDAAP concerns? - Remarks",
		  "Did not Communicate or threaten to communicate false credit information or information which should be known to be false and utilized the proper CBR script whenever a consumer enquires about that? - Remarks",
		  "Handle the consumers dispute correctly and take appropriate action including providing the consumer with the correct contact information to submit a written dispute or complaint or offer to escalate the call? - Remarks",
		  "Did not Make the required statement on time barred accounts indicating that the consumer cannot be pursued with legal action? - Remarks",
		  "Adhere to FDCPA  laws? - Remarks",
		  "Did not Make any statement that could be considered discriminatory towards a consumer or a violation ECOA policy? - Remarks",
		  "Did the collectors adhere to the State Restrictions? - Remarks",
		  "Confirm with consumer if he/she is the authorized user of the debit or credit card / checking account? - Remarks",
		  "Recap the call by verifying consumers Name Address CC/AP information? - Remarks",
		  "Stated the proper payment script before processing payment?   - Remarks",
		  "Obtain permission from the consumer to initiate electronic credit /debit card transactions or through checking account and get supervisor verification if needed?**SQ** - Remarks",
		  "Educate the consumer about correspondence being sent (Receipts PIF SIF Confirmations etc)? - Remarks",
		  "In case of PDCs did the Collector asks for permission to call the Consumer back if it is declined or there is an issue with the payment?  - Remarks",
		  "Demonstrate Active Listening? - Remarks",
		  "Represent the company and the client in a positive manner? - Remarks",
		  "Anticipate and overcome objections? - Remarks",
		  "Transfer call to My Quick Wallet's support appropriately (if applicable)? - Remarks",
		  "Summarize the call? - Remarks",
		  "Provided My Quick Wallet's support number incase its required (if applicable)? - Remarks",
		  "Set appropriate timelines and expectations for follow up? - Remarks",
		  "Close the call Professionally? - Remarks",
		  "Use the proper action code? - Remarks",
		  "Use the proper result code? - Remarks",
		  "Document thoroughly the context of the conversation? - Remarks",
		  "Did the rep document the callback permission on the account as per Reg F policy? - Remarks",
		  "Remove any phone numbers known to be incorrect?**SQ** - Remarks",
		  "Update address information if appropriate?**SQ** - Remarks",
		  "Change the status of the account, if appropriate?**SQ** - Remarks",
		  "Escalate the account to a supervisor for handling, if appropriate? - Remarks",

       "Call Summary","Audit Start date and  Time ", "Audit End Date and  Time"," Call Interval",  "Feedback", "Agent Review Date/Time", "Agent Comment", "Mgnt Review Date/Time","Mgnt Review By", "Mgnt Comment","Client Review Name","Client Review Note","Client Review Date " );